export const DEFAULT_ACTION = 'app/Search/DEFAULT_ACTION';

export const SEARCH_LOCATION = 'app/Search/SEARCH_LOCATION';
export const SEARCH_LOCATION_SUCCESS = 'app/Search/SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAIL = 'app/Search/SEARCH_LOCATION_FAIL';
